name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - id: cache
        name: Yarn Cache Dir
        run: echo "::set-output name=value::$(yarn cache dir)"
      - name: Restore Lockfile
        uses: actions/cache@v2
        with:
          path: yarn.lock
          key: yarn-lock-${{ github.sha }}
          restore-keys: yarn-lock-
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache.outputs.value }}
          key: yarn-cache-${{ github.sha }}
          restore-keys: yarn-cache-
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        if: ${{ github.repository == 'satorijs/protocol' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: .vuepress/dist
          publish_branch: pages
          external_repository: satorijs/satorijs.github.io
          force_orphan: true
